### ISSUE TITLE
Self-explanatory UI for first time users

### ISSUE THREAD

**Issue by communitydriven** [peterhil/spellbook#32]
(Sorry for Bad english) When clicking on the Button right to the CategoryField it should open the DropDownMenu longer, where we can see all the Folders, because now i can not see all my Folders.

There are Solutions to this how to do it:
-On clicking to the Button a new windows opens instead the Dropdown menu.
-Make the Dropdown menu longer that we can see the subfolders too

Maybe I can help you when i have instelled the Development Tools.

**Comment by peterhil** [comment]
Oh, I should improve the documentation. Try searching for a category on the input field – that is the main way of using this. The dropdown only shows last five categories, where a bookmark has been saved.

**Comment by peterhil** [comment]
When you have done a search and selected a category, you can see the subcategories by clicking the button with the minus sign, and add a subcategory by clicking the button with the plus sign and gicing the subcategory name.

**Comment by peterhil** [comment]
You can use the extension by keyboard only. The arrows, enter and tab keys work as expected with web forms.

**Comment by peterhil** [comment]
The user interface should be more self-explanatory for first time users:

* [x] Make it obvious that you can scroll the search results
* [x] Icons should be better
* [x] Dropdowns should have titles
* [x] Add headings to dropdowns (style like the toast on no results)
* [x] Show number of search results
* [x] Show number of subcategories
