### ISSUE TITLE
Could the list of recent categories automatically show and their number be increased?

### ISSUE THREAD

**Issue by minshifu** [peterhil/spellbook#84]
Thank you for this excellent addon. Could the list of recent categories( folders) automatically show without having to press the button? Currently only 5 categories show. Could more be supported? Best regards!

![图片](https://user-images.githubusercontent.com/5119952/184904837-c314489d-5810-4583-bb8f-b66889f40343.png)

**Comment by peterhil** [comment]
Thank you for your input! I would rather not present recent categories by default as the space on the popup is quite limited, but you can open them quickly by hitting tab and space (after opening the popup – possibly with a shortcut key which is something like Ctrl-E or Ctrl-Alt-E for version 0.5.0 and will change to Alt-S on version 0.6.0).

I had thought of having a user option for the amount of recent categories, but for now gave up on the idea, as the space on the popup is limited...

PS. Did you notice that you can seach the categories from the category input field?
